Import('RTT_ROOT')
Import('rtconfig')

comm = rtconfig.ARCH + '/common'
path = rtconfig.ARCH + '/' + rtconfig.CPU

# The set of source files associated with this SConscript file.
if rtconfig.PLATFORM == 'armcc':
	src = Glob(path + '/*.c') + Glob(path + '/*_rvds.S') + Glob(comm + '/*.c')

if rtconfig.PLATFORM == 'gcc':
	src = Glob(path + '/*.c') + Glob(path + '/*_gcc.S') + Glob(comm + '/*.c') + Glob(path + '/*_init.S')

if rtconfig.PLATFORM == 'iar':
	src = Glob(path + '/*.c') + Glob(path + '/*_iar.S') + Glob(comm + '/*.c')

if rtconfig.PLATFORM == 'cl':
	src = Glob(path + '/*.c')

if rtconfig.PLATFORM == 'mingw':
	src = Glob(path + '/*.c')

inc = [RTT_ROOT + '/cpu/' + rtconfig.ARCH + '/' + rtconfig.CPU, RTT_ROOT + '/cpu/' + rtconfig.ARCH + '/common']
group = {'src' : src, 'inc' : inc}

Return('group')
