import os

src   = [Glob('drivers/misc/*.c')]
src  += [Glob('drivers/serial/*.c')]
src  += [Glob('drivers/src/*.c')]

inc   = [
    os.path.abspath('./finsh'),
    os.path.abspath('./Inc'),
    os.path.abspath('./include'),
    os.path.abspath('./drivers/include')
]

group = {'src' : src, 'inc' : inc}

Return('group')
