import os
import rtconfig

# get current directory
cwd = os.path.abspath('.')

# The set of source files associated with this SConscript file.
src = [
cwd+'/CMSIS/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c',
]

src += Glob('STM32F4xx_StdPeriph_Driver/src/*.c')


#add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
     src = src + [cwd+'/CMSIS/ST/STM32F4xx/Source/Templates/gcc_ride7/startup_stm32f4xx.s']
elif rtconfig.CROSS_TOOL == 'keil':
     src = src + [cwd+'/CMSIS/ST/STM32F4xx/Source/Templates/arm/startup_stm32f4xx.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src = src + [cwd+'CMSIS/ST/STM32F4xx/Source/Templates/iar/startup_stm32f4xx.s']

inc = [cwd + '/STM32F4xx_StdPeriph_Driver/inc', 
    cwd + '/CMSIS/ST/STM32F4xx/Include',
    cwd + '/CMSIS/Include']

group = {'src' : src, 'inc' : inc}

Return('group')
